/* 
* @Author: zhanghan
* @Date:   2015-02-07 16:39:17
* @Last Modified by:   zhanghan
* @Last Modified time: 2015-02-07 16:39:20
*/

'use strict';

// celebreties is actually the roster of New England Patriots, plus my name, plus some of my friends names.
var celebreties = ['Angel M. Perez Torres', 'Han Zhang', 'Matt Stewart',
'Danny Aiken',
'Ryan Allen',
'Danny Amendola',
'Kyle Arrington',
'Akeem Ayers',
'LeGarrette Blount',
'Brandon Bolden',
'Josh Boyce',
'Tom Brady',
'Alan Branch',
'Brandon Browner',
'Malcolm Butler',
'Marcus Cannon',
'Jonathan Casillas',
'Patrick Chung',
'Jamie Collins',
'Dan Connolly',
'James Develin',
'Jordan Devey',
'Nate Ebner',
'Julian Edelman',
'Cameron Fleming',
'Darius Fleming',
'Jimmy Garoppolo',
'Stephen Gostkowski',
'Jonas Gray',
'Rob Gronkowski',
'Duron Harmon',
'Dont\'a Hightower',
'Michael Hoomanawanui',
'Chandler Jones',
'Chris Jones',
'Josh Kline',
'Brandon LaFell',
'Devin McCourty',
'Zach Moore',
'Rob Ninkovich',
'Darrelle Revis',
'Logan Ryan',
'Sealver Siliga',
'Matthew Slater',
'Nate Solder',
'Bryan Stork',
'Brian Tyms',
'Joe Vellano',
'Shane Vereen',
'Sebastian Vollmer',
'Ryan Wendell',
'Chris White',
'James White',
'Vince Wilfork',
'Tavon Wilson',
'Tim Wright',
];